CREATE TABLE States (
	Id	INT		NOT NULL,
	StateName	VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_States PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE Contacts (
	Id	INT		IDENTITY (1, 1) NOT NULL,
	FirstName VARCHAR(50) NULL,
	LastName VARCHAR(50) Null,
	Email VARCHAR(50) NULL,
	Company VARCHAR(50) Null,
	Title VARCHAR(50) NULL,
	CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE Addresses (
	Id INT	IDENTITY (1, 1) NOT NULL,
	ContactId INT NOT NULL,
	AddressType VARCHAR(10) NOT NULL,
	StreetAddress VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL,
	StateId INT NOT NULL,
	PostalCode VARCHAR(20) NOT NULL,
	CONSTRAINT PK_Addresses PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT FK_Addresses_Contacts FOREIGN KEY (ContactId) REFERENCES Contacts (Id) ON DELETE CASCADE,
	CONSTRAINT FK_Addresses_States FOREIGN KEY (StateId) REFERENCES States (Id)
);